# Generated by Django 5.2.7 on 2025-11-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_load_categorias_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagenes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
