"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # Cargar variables del archivo .env
from corsheaders.defaults import default_headers

# Configuración de Stripe
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar credenciales de Firebase en desarrollo: si existe un archivo de cuenta de servicio
# en la raíz del proyecto y no se ha configurado la variable de entorno, la usamos automáticamente.
if not os.getenv('RUTA_CUENTA_SERVICIO_FIREBASE') and not os.getenv('FIREBASE_SERVICE_ACCOUNT'):
    # Buscar cualquier archivo de cuenta de servicio con patrón *firebase-adminsdk*.json
    candidates = list(BASE_DIR.glob('*firebase-adminsdk*.json'))
    if candidates:
        # usar el primero que encontremos
        os.environ['RUTA_CUENTA_SERVICIO_FIREBASE'] = str(candidates[0])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&szk-&gf1jadg$**)wcymel-ee=c@ktl6s4_)8r3lmo0f63_ac"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

raw_allowed_hosts = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,web-production-de7b5.up.railway.app",
)
ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "corsheaders",
    "authz",
    "rest_framework",
    "rest_framework.authtoken",
    "scikit_learn_ia",
    "tienda",
    "reportes",
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
raw_cors_origins = os.getenv(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,"
    "https://web-production-de7b5.up.railway.app",
)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in raw_cors_origins.split(",") if origin.strip()
]

# Permitir el header Authorization en CORS (por si falta)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'Authorization',
]

# Configuración de DRF: habilitar TokenAuthentication por defecto (acepta `Authorization: Token <key>`)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Opcional: puedes añadir DEFAULT_PERMISSION_CLASSES si lo deseas
}
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "railway",
        "USER": "postgres",
        "PASSWORD": "ZxgRFAAVgcNNNsyeWrHjVzMndyvsAJYW",
        "HOST": "switchback.proxy.rlwy.net",
        "PORT": "37915",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Configuración de OpenAI
def get_openai_key():
    """
    Obtiene la API Key de OpenAI para la cuenta gratuita.
    Prioridad: 1. Variable entorno → 2. Key de desarrollo (opcional).
    """
    # 1. Variable de entorno (producción)
    key = os.getenv("OPENAI_API_KEY")

    # Si quieres, puedes poner aquí una key de desarrollo por defecto:
    # if not key:
    #     key = "sk-xxxxx_TU_KEY_DE_DESARROLLO"

    return key  


OPENAI_API_KEY = get_openai_key()

